### ISSUE TITLE
Implement jquery

### ISSUE THREAD

**Issue by ronnygunawan** [teknologi-umum/decimal-clock#7]
Note: while jQuery is not a bleeding edge technology, A submission written in jQuery is perfect for serving as a baseline frontend framework.

- All rendering and logics should be written in jQuery API
- Do not write anything else other than jQuery API calls
- Do not use any other 3rd party libraries

**Comment by the-supernova** [comment]
#33 
Please look if my PR passes all the requirements

**Comment by ronnygunawan** [comment]
Implemented in #33 
Thank you @the-supernova
